version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3308:3306  # Corrected port mapping
    volumes:
      - db:/var/lib/mysql

  timesheet-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8082:6868
    volumes:
      - .m2:/root/.m2
    stdin_open: true

volumes:
  db:
