version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  timesheet-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8082:6868
    volumes:
      - .m2:/root/.m2
    stdin_open: true

volumes:
  db :
