version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    depends_on:
      - mysqldb
    image: 14326410/stockmgt-devops:1.0.0
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db_stock?createDatabaseIfNotExist=true"
        "spring.datasource.username": "root",
        "spring.datasource.password":
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true


volumes:
  db: